### ISSUE TITLE
Error when running bash run-miner.sh

### ISSUE THREAD

**Issue by officialsahyaboutorabi** [VectorChat/chunking_subnet#9]
I get this following error when I try to run the miner.

0|chunking | │    28 from nltk.tokenize import sent_tokenize                                │
0|chunking | ╰──────────────────────────────────────────────────────────────────────────────╯
0|chunking | ModuleNotFoundError: No module named 'chunking'
0|chunking | ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
0|chunking | │ /home/user/chunking_subnet/neurons/miner.py:25 in <module>                   │
0|chunking | │                                                                              │
0|chunking | │    22                                                                        │
0|chunking | │    23 import bittensor as bt                                                 │
0|chunking | │    24                                                                        │
0|chunking | │ ❱  25 from chunking.base.miner import BaseMinerNeuron                        │
0|chunking | │    26 from chunking.protocol import chunkSynapse                             │
0|chunking | │    27                                                                        │
0|chunking | │    28 from nltk.tokenize import sent_tokenize                                │
0|chunking | ╰──────────────────────────────────────────────────────────────────────────────╯
0|chunking | ModuleNotFoundError: No module named 'chunking'

**Comment by VectorChat** [comment]
Hey @officialsahyaboutorabi, it looks like you need to run `pip3 install -e .` in your virtual environment. Did you use `setup.sh` when setting up your machine for mining? We would also be able to help easier in the discord subnet channel.

**Comment by officialsahyaboutorabi** [comment]
I did run the `pip3 install -e .` command, however nothing changed, the same error still.

**Comment by VectorChat** [comment]
Have you tried adding `PYTHONPATH=.` to your `.env` file?

**Comment by officialsahyaboutorabi** [comment]
I also tried that. I fixed the error because of an issue with finding the folder. I basically copied the chunking folder into where the miner script is and that fixed it.
